import Link from "next/link";
import './globals.css';
import '@/styles/Home.module.css';
import '@/styles/globals.css';

export default function RootLayout ( {
  children,
  sidebar,
  modal,
}: {
  children: React.ReactNode;
  sidebar: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html>
      <head></head>
      <body>
        <main>
          <nav>
            <Link href="/">Home</Link> |{' '}
            <Link href="/notes">Notes</Link>
          </nav>
          <br />
          {children}
          <hr />
          Sidebar: {sidebar}
          <hr />
          Modal:
          {modal}
        </main>
      </body>
    </html>
  );
}

// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
